### ISSUE TITLE
希望能動詞名詞句子語氣歸類 

### ISSUE THREAD

**Issue by Yutii** [rogeraabbccdd/Fadacai-Generator#4]
希望能分門歸類，載排列語句時能更快速找到適合的字句

**Comment by jikker** [comment]
我覺得是 按照字數排序就好 也比較好做

**Comment by lejoiedevivre** [comment]
順便希望 可以 
高 雄 發 大 財
每個字都獨立做出來讓大家玩

**Comment by rogeraabbccdd** [comment]
目前已按照中文字排序
截至目前有超過500個音檔，如果要照語氣或詞性歸類的話會很耗時間

**Comment by rogeraabbccdd** [comment]
目前已照字數分區，每區可折疊，區內照字數排序
![chrome_qJwTpXSFWu](https://user-images.githubusercontent.com/15815422/58385388-305aa100-8022-11e9-9084-79e9437f0a72.png)
