### ISSUE TITLE
音檔之間的空白過久，不夠流暢

### ISSUE THREAD

**Issue by tenz** [rogeraabbccdd/Fadacai-Generator#8]
目前音檔間的空白長達一秒以上，如果能連貫，效果更好

**Comment by rogeraabbccdd** [comment]
在 26213d619d28451f866114ce2b35712c2b26eec9 調整了音檔的載入時機，播放時應該會更流暢  
剩下的間隔就是音檔本身的空白

**Comment by rogeraabbccdd** [comment]
在 6ebc3939a1a514d152d6f003c1b4115b38ff123a 再次調整音檔載入時機，讀取分享連結時會載入使用的音檔
